repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace  # Trim trailing whitespace
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: double-quote-string-fixer  # Replace double quoted strings with single quoted strings
      - id: end-of-file-fixer  # Make sure files end in a newline and only a newline
      - id: requirements-txt-fixer  # Sort entries in requirements.txt and remove incorrect entry for pkg-resources==0.0.0
      - id: fix-encoding-pragma  # Remove the coding pragma:
        args: [ "--remove" ]
      - id: mixed-line-ending  # Replace or check mixed line ending
        args: [ "--fix=lf" ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  - repo: https://gitee.com/ibopo/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]

#  - repo: https://github.com/psf/black
#    rev: 23.3.0
#    hooks:
#      - id: black
#        language_version: python3.9
#
#  - repo: https://github.com/pycqa/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
#        name: isort (python)
#
#  - repo: https://github.com/Riverside-Healthcare/djLint
#    rev: v1.25.0
#    hooks:
#      - id: djlint-django

  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
      - id: poetry-export
        args: [
          "-f", "requirements.txt",
          "-o", "requirements.txt",
          "--without-hashes"
        ]

#  - repo: https://github.com/charliermarsh/ruff-pre-commit
#    rev: 'v0.0.264'
#    hooks:
#      - id: ruff

#  - repo: git://github.com/matthorgan/pre-commit-conventional-commits
#    rev: master
#    hooks:
#      - id: conventional-commit-check
#        stages:
#          - commit-msg
exclude: |
  (?x)^(
    docs\/.*|
    tests\/.*|
    assets\/.*|
    scripts\/.*|
    runtime\/.*|
    fixtures\/.*|
    credentials\/.*|
    deployments\/.*|
    .envs\/.*|
    .*migrations\/.*|
    \.coveragerc|
    setup\.cfg|
    fabfile\.py|
    .*?proto.*|
    .*?\.html|
    .*?\.yaml|
    .*?\.yml|
    .*?\.css|
    .*?\.pem|
    .*?\.key|
    .*?\.md|
    .*?\.js
  )
#exclude: .*migrations\/.*
default_stages: [ commit ]
